### ISSUE TITLE
Add support for SAI on STM32U5

### ISSUE THREAD

**Issue by tyler-gilbert** [embassy-rs/stm32-data#243]
This doesn't follow any of the sai_vx.yaml patterns. It is a new (and hopefully improved) SAI block.

If no one is working on this, I work on getting a PR ready.

**Comment by tyler-gilbert** [comment]
Correction. The STM32U5 uses the sai_v4. So no MR needed to add the yaml. I will still verify the register map matches V4 and add it to `perimap`.

**Comment by tyler-gilbert** [comment]
The datasheet has a mismatch with `sai_v4`:

```
enum/CKSTR:
  bit_size: 1
  variants:
    - name: FallingEdge
      description: Data strobing edge is falling edge of SCK
      value: 0
    - name: RisingEdge
      description: Data strobing edge is rising edge of SCK
      value: 1
```
<img width="806" alt="ckstr" src="https://github.com/embassy-rs/stm32-data/assets/6136781/83213fe4-82b8-4d7a-a15e-94575b16b165">


Some discussion [here](https://community.st.com/t5/stm32-mcu-products/f446-cube-documentation-saixy-cr1-ckstr/td-p/390523). The ST employee seems to confirm the datasheet is correct.
